DreamToEarn/Controllers/DrawAmountController.cs
using DreamToEarn.DbModel;
using DreamToEarn.Helper;
using DreamToEarn.Models;
using DreamToEarn.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DreamToEarn.Controllers
{
    public class DrawAmountController : AppController
    {
        // GET: DrawAmount
        [HttpGet]
        [Authorize(Roles = "1,2,3")]
        public ActionResult Withdraw()
        {
            var date = DateTime.Now;
            var days = WithDrawRepository.GetAllWithDrawDays();
            ViewBag.isWithdrawDate = "false";

            if (date.Day == days.FirstDay)
                ViewBag.isWithdrawDate = "true";
            if (date.Day == days.SecondDay)
                ViewBag.isWithdrawDate = "true";
            if (date.Day == days.ThirdDay)
                ViewBag.isWithdrawDate = "true";
            if (date.Day == days.ForthDay)
                ViewBag.isWithdrawDate = "true";

            ViewBag.dayOne = days.FirstDay;
            ViewBag.dayTwo = days.SecondDay;
            ViewBag.dayThree = days.ThirdDay;
            ViewBag.dayFour = days.ForthDay;

            var earnings = ViewBag.TotalEarnings = InvestmentPlanRepository.TotalEarnings(CurrentUser.UserId);
            var commisions = ViewBag.TotalCommissions = CommissionRepository.GetUserApprovedCommision(CurrentUser.UserId);
            if (earnings == null)
            {
                earnings = 0;
                ViewBag.TotalEarnings = 0;
            }
            if (commisions == null)
            {
                commisions = 0;
                ViewBag.TotalCommissions = 0;
            }

            if (earnings > 0 || commisions > 0)
                ViewBag.TotalBalance = Convert.ToDecimal(earnings) + Convert.ToDecimal(commisions);// earning should be commission + earnings    
            else
                ViewBag.TotalBalance = 0;

            var usersDetail = UsersRepository.GetUser(CurrentUser.UserId);
            ViewBag.BankAccount = usersDetail.BankAccount.ToDefaultString();
            ViewBag.JazzCash = usersDetail.JazzCash.ToDefaultString();
            ViewBag.EasyPaisa = usersDetail.EasyPaisa.ToDefaultString();
            ViewBag.BankTitle = usersDetail.BankTitle;

            var ex = UsersRepository.GetAllExchanger();
            ViewBag.ExchangerName = $"{ex.FirstName} {ex.LastName}";


            return View();
        }

        [HttpPost]
        [Authorize(Roles = "1,2,3")]
        public JsonResult Withdraw(WithdrawModel model)
        {
            try
            {
                var obj = UsersRepository.GetUser(model.UserId);
                if (model.drawType == "BankAccount")
                {
                    if (obj.BankAccount.ToDefaultString() == "")
                        return Json(new { IsSuccess = false, Message = "Your Bank Account detail is missing, please update your profle before withdraw." }, JsonRequestBehavior.AllowGet);
                }
                if (model.drawType == "JazzCash")
                {
                    if (obj.JazzCash.ToDefaultString() == "")
                        return Json(new { IsSuccess = false, Message = "Your Jazz Cash number is missing, please update your profle before withdraw." }, JsonRequestBehavior.AllowGet);
                }
                if (model.drawType == "EasyPaisa")
                {
                    if (obj.EasyPaisa.ToDefaultString() == "")
                        return Json(new { IsSuccess = false, Message = "Your Easy Paisa number is missing, please update your profle before withdraw." }, JsonRequestBehavior.AllowGet);
                }

                if (WithDrawRepository.IsWithdrawPending(model.UserId) == false)
                {
                    return Json(new { IsSuccess = false, Message = "Your transaction is already in Pending state. You can not withdraw." }, JsonRequestBehavior.AllowGet);
                }
                if (model.totalDraw >= model.totalEarningOnDraw)
                {
                    return Json(new { IsSuccess = false, Message = "Draw amount should be less than then total balance." }, JsonRequestBehavior.AllowGet);
                }

                var deduction = (model.totalDraw * 2.75) / 100;
                var grandTotalDraw = model.totalDraw + deduction;

                if (grandTotalDraw > model.totalEarningOnDraw) // if total draw + deduction is greater than total balance
                {
                    return Json(new { IsSuccess = false, Message = "Please enter less withdraw amount, your balance is insufficient for this request." }, JsonRequestBehavior.AllowGet);
                }
                model.deductions = Convert.ToDecimal(deduction);

                Random random = new Random();
                int OTPToken = random.Next(10000000);

                model.OTPTokens = OTPToken.ToDefaultString();

                var email = new EmailHelper();
                email.emailToAddress = CurrentUser.Email;
                email.subject = "Dream to Earn First Login Token";
                email.body = $"Dear User, <br> <br> Please copy following OTP for your withdraw transaction. <br> <br> Your OTP is <b>{OTPToken}</b> <br><br> Please do not delete this token before withdraw. <br> <br> This is an auto email, please do not reply.";
                email.SendEmail();

                var draw = WithDrawRepository.WithDrawAmount(model);



                return Json(new { IsSuccess = true, Message = "OTP sent" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { IsSuccess = false, Message = "Amount with draw failed" }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        [Authorize(Roles = "1,2,3")]
        public JsonResult VerifyOTPTokens(WithdrawModel model)
        {
            try
            {

                if (WithDrawRepository.VarifyOTPToken(model.OTPTokens, model.UserId))
                {
                    //var deduction = Math.Round((model.totalDraw * 2.75) / 100, 2, MidpointRounding.ToEven);

                    //var totalBalance = model.totalEarningOnDraw;

                    //var totalLeftBalance = totalBalance - model.totalDraw - deduction; //3200 - 3000 - 82.5 = 1717.5
                    //                                                                   //now 82.5 should be added in admin balance; and 1717.5 should be updated to investor commission or earnings

                    //var earnings = model.earnings; //2000
                    //var commissions = model.commissions; //1200                

                    model.drawDate = DateTime.Now;
                    model.drawStatus = true;
                    model.isAdminApprove = false;

                    WithDrawRepository.UpdateWithdrawStatus(model);
                    //make earning zero and add remaining balance to commission

                    //CommissionRepository.DeductCommissions(model.UserId, Convert.ToDecimal(totalLeftBalance));
                    //InvestmentPlanRepository.DeductEarnings(model.UserId, 0);


                    //UsersRepository.UpdateTotalCommissionsForAdmin(Convert.ToDecimal(deduction));

                    return Json(new { IsSuccess = true, Message = "Withdraw successfull, OTP matched" }, JsonRequestBehavior.AllowGet);
                }
                else
                    return Json(new { IsSuccess = false, Message = "Withdraw failed, OTP not matched" }, JsonRequestBehavior.AllowGet);


            }
            catch (Exception ex)
            {
                return Json(new { IsSuccess = false, Message = "Withdraw failed" }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        [Authorize(Roles = "1,3")]
        public ActionResult ApproveWithdraw()
        {
            if (CurrentUser.Role == "1")
                return View(WithDrawRepository.GetAllWithDraws());
            else
                return View(WithDrawRepository.GetAllWithDrawsForExchanger());
        }

        [HttpGet]
        [Authorize(Roles = "2, 3")]
        public ActionResult ViewWithDraw()
        {
            return View(WithDrawRepository.GetUserWithDraws(CurrentUser.UserId));
        }

        [HttpGet]
        [Authorize(Roles = "1")]
        public ActionResult setDrawDates()
        {
            var days = WithDrawRepository.GetAllWithDrawDays();
            ViewBag.dayOne = days.FirstDay;
            ViewBag.dayTwo = days.SecondDay;
            ViewBag.dayThree = days.ThirdDay;
            ViewBag.dayFour = days.ForthDay;
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "1")]
        public ActionResult drawHistory()
        {
            var totalYTDWithdraw = WithDrawRepository.getTotalYTDApprovedWithdraws();
            var lastWithDraw = WithDrawRepository.getLastApprovedWithdraws();
            ViewBag.totalYTDWithdraw = totalYTDWithdraw;
            ViewBag.lastWithDraw = lastWithDraw;  
            
            return View(WithDrawRepository.GetAllApprovedWithDraws());
        }

        [HttpPost]
        [Authorize(Roles = "1")]
        public JsonResult setDrawDates(int dayOne, int dayTwo, int dayThree, int dayFour)
        {
            try
            {
                WithDrawRepository.addDrawDays(dayOne, dayTwo, dayThree, dayFour);

                return Json(new { IsSuccess = true, Message = "Withdraw days added successfull" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { IsSuccess = false, Message = "Adding Withdraw days fail" }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [Authorize(Roles = "1,3")]
        public JsonResult ApproveWithdraw(int drawId, int UserId)
        {
            try
            {
                var model = WithDrawRepository.GetAllWithDraws(drawId);

DreamToEarn/Views/DrawAmount/ApproveWithdraw.cshtml
@model IEnumerable<DreamToEarn.DbModel.UsersWithdraw>

@using System.Security.Claims;
@using DreamToEarn.Helper;
@{
    var user = new AppUser(User as ClaimsPrincipal);

    if (Session["SiteSessions"] == null)
    {
        Response.Redirect("/Account/Login");
        Response.End();
    }
}

@{
    ViewBag.Title = "Approve Withdraw";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}


<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table mr-1"></i>
        View / Approve Withdraw
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>User Name</th>
                        <th>Total Balance On Draw</th>
                        <th>Total Withdraw</th>
                        <th>Total Deductions</th>
                        <th>With Draw Date</th>
                        <th>Draw Type</th>
                        <th>Account</th>
                        @if (user.IsInRole("1"))
                        {
                            <th>Action</th>

                        }
                        @if (user.IsInRole("3"))
                        {
                            <th>Action</th>

                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.FirstName @item.LastName
                            </td>
                            <td>
                                @item.UserName
                            </td>
                            <td>
                                @item.totalEarningOnDraw /RS
                            </td>
                            <td>
                                @item.totalDraw /RS
                            </td>
                            <td>
                                @item.Deductions / RS
                            </td>
                            <td>
                                @item.drawDate
                            </td>
                            <td>
                                @item.DrawType
                            </td>
                            <td>
                                @if (item.DrawType == "EasyPaisa")
                                {
                                    <span> @item.EasyPaisa</span>
                                }
                                @if (item.DrawType == "JazzCash")
                                {
                                    <span> @item.JazzCash</span>
                                }
                                @if (item.DrawType == "BankAccount")
                                {
                                    <span> @item.BankAccount -  @item.BankTitle</span>
                                }
                            </td>
                            <td>
                                @if (user.IsInRole("1"))
                                {
                                    if (item.isAdminApprove == true && item.drawSentByExchanger == true)
                                    {
                                        <span class="alert alert-success"> Approved</span>
                                    }
                                    else if (item.isAdminApprove == false && item.drawSentByExchanger == false)
                                    {
                                        <a href="" class="small text-danger" onclick="return approveWithdraw(@item.drawID, @item.UserId)">Approve this? </a>
                                    }
                                    else
                                    {
                                        <span class="alert alert-success"> Pending for Exchanger</span>
                                    }
                                }

                                @if (user.IsInRole("3"))
                                {
                                    if (item.isAdminApprove == true && item.drawSentByExchanger == true)
                                    {
                                        <span class="alert alert-success"> All Approved</span>
                                    }
                                    else
                                    {
                                        <a href="" class="small text-danger" onclick="return approveExchangerWithdraw(@item.drawID, @item.UserId)">Approve this? </a>
                                    }
                                }

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div id="lblmsg"></div>
<div id="snackbar"></div>
<script>
    function approveExchangerWithdraw(drawId, userID) {
        if (!confirm('Are you sure you want to approve this withdraw?')) {
            return false;
        }
            var url = '@Url.Action("ApproveExchangerWithdraw", "DrawAmount")';
             $.ajax({
                type: "POST",
                 url: url,
                 data: { drawId: drawId, UserId: userID },
                success: function (result) {
                    if (result.IsSuccess) {
                        ShowMessage('success', result.Message);
                        $("#lblmsg").removeClass("small text-danger");
                        $("#lblmsg").addClass("smail text-success");
                        document.getElementById('lblmsg').innerHTML = result.Message;
                        $('#ddlPlan').val('');
                        window.location.reload();
                    }
                    else {
                        ShowMessage('', "NOTE: " + result.Message);
                        $("#lblmsg").removeClass("small text-success");
                        $("#lblmsg").addClass("smail text-danger");
                        document.getElementById('lblmsg').innerHTML = "NOTE: " + result.Message;
                    }
                },
                error: function (jqXHR, status, err) {
                    ShowMessage('', "NOTE: " + result.Message);
                    $("#lblmsg").removeClass("small text-success");
                    $("#lblmsg").addClass("smail text-danger");
                    document.getElementById('lblmsg').innerHTML = "NOTE: " + result.Message;
                }
            });
    }
    function approveWithdraw(drawId, userID) {
        if (!confirm('Are you sure you want to approve this withdraw?')) {
            return false;
        }
            var url = '@Url.Action("ApproveWithdraw", "DrawAmount")';
             $.ajax({
                type: "POST",
                 url: url,
                 data: { drawId: drawId, UserId: userID },
                success: function (result) {
                    if (result.IsSuccess) {
                        ShowMessage('success', result.Message);
                        $("#lblmsg").removeClass("small text-danger");
                        $("#lblmsg").addClass("smail text-success");
                        document.getElementById('lblmsg').innerHTML = result.Message;
                        $('#ddlPlan').val('');
                        window.location.reload();
                    }
                    else {
                        ShowMessage('', "NOTE: " + result.Message);
                        $("#lblmsg").removeClass("small text-success");
                        $("#lblmsg").addClass("smail text-danger");
                        document.getElementById('lblmsg').innerHTML = "NOTE: " + result.Message;
                    }
                },
                error: function (jqXHR, status, err) {
                    ShowMessage('', "NOTE: " + result.Message);
                    $("#lblmsg").removeClass("small text-success");
                    $("#lblmsg").addClass("smail text-danger");
                    document.getElementById('lblmsg').innerHTML = "NOTE: " + result.Message;
                }
            });
    }

      function ShowMessage(type, message) {
             var x = document.getElementById("snackbar");
             x.className = "show";
             x.innerHTML = message;
              setTimeout(function(){ x.className = x.className.replace("show", ""); }, 3000);
        }
</script>

DreamToEarn/Views/DrawAmount/ViewWithDraw.cshtml
@model IEnumerable<DreamToEarn.DbModel.UsersWithdraw>

@using System.Security.Claims;
@using DreamToEarn.Helper;
@{
    var user = new AppUser(User as ClaimsPrincipal);

    if (Session["SiteSessions"] == null)
    {
        Response.Redirect("/Account/Login");
        Response.End();
    }
}

@{
    ViewBag.Title = "Approve Withdraw";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}


<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table mr-1"></i>
        View Withdraws
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Total Balance On Draw</th>
                        <th>Total Withdraw</th>
                        <th>Total Deductions</th>
                        <th>With Draw Date</th>
                        <th>Draw Type</th>
                        <th>Draw Sent Date</th>
                        <th>Status</th>                        
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.FirstName @item.LastName
                            </td>
                            <td>
                                @item.totalEarningOnDraw /RS
                            </td>
                            <td>
                                @item.totalDraw /RS
                            </td>
                            <td>
                                @item.Deductions / RS
                            </td>
                            <td>
                                @item.drawDate
                            </td>
                            <td>
                                @item.DrawType
                            </td>
                            <td>
                                @item.DrawSentDate
                            </td>
                            <td>
                                @if (item.isAdminApprove == true && item.drawSentByExchanger == true)
                                {
                                    <span class="alert alert-success"> Payment Sent </span>
                                }
                                else
                                {
                                    <span class="alert alert-danger"> Pending</span>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

DreamToEarn/Views/DrawAmount/setDrawDates.cshtml
@using System.Security.Claims;
@using DreamToEarn.Helper;
@{
    var user = new AppUser(User as ClaimsPrincipal);

    if (Session["SiteSessions"] == null)
    {
        Response.Redirect("/Account/Login");
        Response.End();
    }
}

@{
    ViewBag.Title = "Set Draw days";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<section>
    <div>
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Set Withdraw Days
        </div>
        <div class="container"></div>
        <div class="border border-light">
            <div class="card-body">
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="mb-1" for="one">First Day</label>
                            <select class=".1-30 form-control bx-selection" id="one" style="width: 320px;">
                                @for (int i = 1; i <= 30; i++)
                                {
                                    <option value="@i">@i</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="mb-1" for="two">Second Day</label>
                            <select class=".1-30 form-control bx-selection" id="two" style="width: 320px;">
                                @for (int i = 1; i <= 30; i++)
                                {
                                    <option value="@i">@i</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="mb-1" for="three">Third Day</label>
                            <select class=".1-30 form-control bx-selection" id="three" style="width: 320px;">
                                @for (int i = 1; i <= 30; i++)
                                {
                                    <option value="@i">@i</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="mb-1" for="four">Forth Day</label>
                            <select class=".1-30 form-control bx-selection" id="four" style="width: 320px;">
                                @for (int i = 1; i <= 30; i++)
                                {
                                    <option value="@i">@i</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="form-group mt-4 mb-0"><a class="btn btn-primary btn-block" href="#" onclick="return AddDrawDays();" style="width:180px">Add</a></div>
                </div>
                <div class="dropdown-divider"></div>
                <table class="table">
                    <tr>
                        <td><b>First Withdraw Date </b></td>
                        <td><b>Second Withdraw Date</b></td>
                        <td><b>Third Withdraw Date</b></td>
                        <td><b>Fourth Withdraw Date</b></td>
                    </tr>
                    <tr>
                        <td>
                            @if (ViewBag.dayOne == 0)
                            {
                                <span class="text-sm-center"> 01/@DateTime.Now.Month/@DateTime.Now.Year</span>
                            }
                            else
                            {
                                <span class="text-sm-center"> @ViewBag.dayOne/@DateTime.Now.Month/@DateTime.Now.Year</span>
                            }
                        </td>
                        <td>
                            @if (ViewBag.dayTwo == 0)
                            {
                                <span class="text-sm-center"> 01/@DateTime.Now.Month/@DateTime.Now.Year</span>
                            }
                            else
                            {
                                <span class="text-sm-center"> @ViewBag.dayTwo/@DateTime.Now.Month/@DateTime.Now.Year</span>
                            }
                        </td>
                        <td>
                            @if (ViewBag.dayThree == 0)
                            {
                                <span class="text-sm-center"> 01/@DateTime.Now.Month/@DateTime.Now.Year</span>
                            }
                            else
                            {
                                <span class="text-sm-center"> @ViewBag.dayThree/@DateTime.Now.Month/@DateTime.Now.Year</span>
                            }
                        </td>
                        <td>
                            @if (ViewBag.dayFour == 0)
                            {
                                <span class="text-sm-center"> 01/@DateTime.Now.Month/@DateTime.Now.Year</span>
                            }
                            else
                            {
                                <span class="text-sm-center"> @ViewBag.dayFour/@DateTime.Now.Month/@DateTime.Now.Year</span>
                            }
                        </td>
                    </tr>
                </table>
            </div>
            <div id="lblmsg"></div>
        </div>
    </div>
    <div id="snackbar"></div>
</section>
<script>


    function AddDrawDays() {
        var one = $('#one').val();
        var two = $('#two').val();
        var three = $('#three').val();
        var four = $('#four').val();

        var url = '@Url.Action("setDrawDates", "DrawAmount")';

        $.ajax({
        type: "POST",
        url: url,
            data: {
                dayOne: one, dayTwo: two, dayThree: three, dayFour: four
        },
        success: function (result) {
            if (result.IsSuccess) {
                $("#lblmsg").removeClass("smail text-danger");
                $("#lblmsg").addClass("small text-success");
                document.getElementById('lblmsg').innerHTML = "Days updated";
                ShowMessage('success', "days updated");
                window.location.reload();
            }
            else {
                $("#lblmsg").removeClass("small text-success");
                $("#lblmsg").addClass("smail text-danger");
                document.getElementById('lblmsg').innerHTML = result.Message;
                ShowMessage('', result.Message);
            }
        },
            error: function (jqXHR, status, err) {
                $("#lblmsg").removeClass("small text-success");
                $("#lblmsg").addClass("smail text-danger");
                document.getElementById('lblmsg').innerHTML = "Can't able to fullfill request, please try later";
                ShowMessage('', "Can't able to fullfill request, please try later");
        }
    });
    }

    function ShowMessage(type, message) {
             var x = document.getElementById("snackbar");
             x.className = "show";
             x.innerHTML = message;
              setTimeout(function(){ x.className = x.className.replace("show", ""); }, 3000);
        }
</script>