DreamToEarn/Controllers/InvestmentPlanController.cs
using DreamToEarn.Helper;
using DreamToEarn.Models;
using DreamToEarn.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DreamToEarn.Controllers
{
    public class InvestmentPlanController : AppController
    {
        // GET: InvestmentPlan
        public ActionResult Index()
        {            
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "1, 2, 3")]
        public ActionResult threeMonthPlan()
        {
            int daysLeft = InvestmentPlanRepository.TotalInvestmentPlanDaysLeft(CurrentUser.UserId);
            if(daysLeft <= 0)
            {
                InvestmentPlanRepository.InactivetPlan(CurrentUser.UserId);
            }

            return View(InvestmentPlanRepository.GetInvestmentPlans(CurrentUser.UserId).AsEnumerable());
        }

        [HttpPost]
        [Authorize(Roles = "1, 2, 3")]
        public JsonResult threeMonthPlan(InvestmentPlanModel model)
        {
            try
            {                
                if (InvestmentPlanRepository.IsPlanExistForUser(model.userId))
                {
                    return Json(new { IsSuccess = false, Message = "Active Plan already exist for this user" }, JsonRequestBehavior.AllowGet);
                }
                var user = InvestmentPlanRepository.AddUpdateinvestmentPlan(model);
                return Json(new { IsSuccess = true, Message = "Plan added successfully!" }, JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                return Json(new { IsSuccess = false, Message = "Plan not added" }, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpGet]
        [Authorize(Roles = "1, 2, 3")]
        public ActionResult SixMonthPlan()
        {
            int daysLeft = InvestmentPlanRepository.TotalInvestmentPlanDaysLeft(CurrentUser.UserId);
            if (daysLeft <= 0)
            {
                InvestmentPlanRepository.InactivetPlan(CurrentUser.UserId);
            }

            return View(InvestmentPlanRepository.GetInvestmentPlans(CurrentUser.UserId).AsEnumerable());
        }

        [HttpPost]
        [Authorize(Roles = "1, 2, 3")]
        public JsonResult SixMonthPlan(InvestmentPlanModel model)
        {
            try
            {
                if (InvestmentPlanRepository.IsPlanExistForUser(model.userId))
                {
                    return Json(new { IsSuccess = false, Message = "Plan already exist for this user" }, JsonRequestBehavior.AllowGet);
                }
                var user = InvestmentPlanRepository.AddUpdateinvestmentPlan(model);
                return Json(new { IsSuccess = true, Message = "Plan added successfully!" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { IsSuccess = false, Message = "Plan not added" }, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpGet]
        [Authorize(Roles = "1")]
        public ActionResult ViewAllInvestment()
        {
            return View(InvestmentPlanRepository.GetAllInvestmentPlanDetail());
        }       

        [HttpGet]
        [Authorize(Roles = "1")]
        public ActionResult ApproveInvestmentForUser(string UserId)
        {            
            return View(InvestmentPlanRepository.GetInvestmentPlanDetail(Convert.ToInt32(UserId)));
        }

        [HttpPost]
        [Authorize(Roles = "1")]
        public JsonResult ApproveInvestmentForUser(InvestmentPlanModel model)
        {
            try
            {                
                var user = InvestmentPlanRepository.AddUpdateinvestmentPlan(model);
                return Json(new { IsSuccess = true, Message = "Plan added successfully!" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { IsSuccess = false, Message = "Plan not added" }, JsonRequestBehavior.AllowGet);
            }

        }
        [HttpPost]
        [Authorize(Roles = "1")]
        public JsonResult InactiveInvestmentForUser(string planId)
        {
            try
            {
                var user = InvestmentPlanRepository.InactiveinvestmentPlan(Convert.ToInt32(planId));
                return Json(new { IsSuccess = true, Message = "Plan inactive successfully!" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { IsSuccess = false, Message = "Plan not added" }, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpGet]
        [Authorize(Roles = "1")]
        public ActionResult AdjustInvestmentForUser(string UserId)
        {            
            return View(InvestmentPlanRepository.GetInvestmentPlanDetail(Convert.ToInt32(UserId)));
        }

        [HttpPost]
        [Authorize(Roles = "1")]
        public JsonResult AdjustInvestmentForUser(InvestmentPlanModel model)
        {
            try
            {
                var user = InvestmentPlanRepository.AdjustEarnings(model);
                return Json(new { IsSuccess = true, Message = "Investment Earnings Adjusted successfully!" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { IsSuccess = false, Message = "Investment Earnings not Adjusted " }, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost]
        [Authorize(Roles = "1")]
        public JsonResult UpdateInvestment(InvestmentPlanModel model)
        {
            try
            {
                var user = InvestmentPlanRepository.UpdateinvestmentPlanPercentage(model);
                return Json(new { IsSuccess = true, Message = "Investment Updated successfully!" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { IsSuccess = false, Message = "Investment not Updated " }, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost]
        [Authorize(Roles = "1")]
        public JsonResult DeleteInvestmentForUser(InvestmentPlanModel model)
        {
            try
            {
                var user = InvestmentPlanRepository.DeleteinvestmentPlan(model);
                return Json(new { IsSuccess = true, Message = "Plan removed successfully!" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { IsSuccess = false, Message = "Plan not removed, error" }, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

DreamToEarn/Views/InvestmentPlan/AdjustInvestmentForUser.cshtml
@model IEnumerable<DreamToEarn.DbModel.UsersDetail>
@{
    ViewBag.Title = "AdjustInvestmentForUser";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}


<section>
    <div>
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Add Ads
        </div>
        <div class="card-body">
            <div class="form-row">
                <div class="col-md-6">
                    @foreach (var item in Model)
                    {
                        if (item.IsActive == true)
                        {
                            <div class="form-group">
                                <label class="small mb-1" for="earnings">Adjust Earnings for @item.FirstName @item.LastName</label>
                                <input class="form-control py-4" id="earnings" type="number" placeholder="Enter earnings" value="@item.TotalEarnings" />
                                <label class="small text-danger" for="earnings">Please make sure before updating / Adjusting earning, it is not revertable</label>
                                <input class="form-control py-4" id="userId" type="hidden" value="@item.UserId" />
                            </div>
                        }
                    }
                </div>
            </div>
            <div class="form-group mt-4 mb-0"><a class="btn btn-primary btn-block" href="#" onclick="return AdjustEarnings();" style="width:280px">Adjust Investment</a></div>
            <div id="lblmsg"></div>
        </div>
    </div>

    <div id="snackbar"></div>
</section>
<script>
    function AdjustEarnings() {
            if (!confirm('Are you sure you want to Adjust earnings for this user?')) {
                return false;
            }
            var earnings = $('#earnings').val();
            var id = $("#userId").val();
            if (earnings == "") {
                ShowMessage("", "Please enter earnings");
                return false;
            }

            var url = '@Url.Action("AdjustInvestmentForUser", "InvestmentPlan")';
            var modelObj = {
                totalEarnings: earnings,
                userId: id
            };

             $.ajax({
                type: "POST",
                url: url,
                data: {
                    model: modelObj
                },
                success: function (result) {
                    if (result.IsSuccess) {
                         $("#lblmsg").removeClass("smail text-danger");
                        $("#lblmsg").addClass("small text-success");
                        document.getElementById('lblmsg').innerHTML = result.Message;
                        ShowMessage('success', result.Message);
                        window.location = "/dashboard/index";
                    }
                    else {
                        $("#lblmsg").removeClass("small text-success");
                        $("#lblmsg").addClass("smail text-danger");
                        document.getElementById('lblmsg').innerHTML = result.Message;
                        ShowMessage('', result.Message);
                    }
                },
                 error: function (jqXHR, status, err) {
                        $("#lblmsg").removeClass("small text-success");
                        $("#lblmsg").addClass("smail text-danger");
                        document.getElementById('lblmsg').innerHTML = "Can't able to change password, please try later";
                        ShowMessage('', "Can't able to change password, please try later");
                }
            });

    }
    function ShowMessage(type, message) {
             var x = document.getElementById("snackbar");
             x.className = "show";
             x.innerHTML = message;
              setTimeout(function(){ x.className = x.className.replace("show", ""); }, 3000);
        }
</script>

DreamToEarn/Views/InvestmentPlan/ApproveInvestmentForUser.cshtml
@model IEnumerable<DreamToEarn.DbModel.UsersDetail>

@using System.Security.Claims;
@using DreamToEarn.Helper;
@{
    var user = new AppUser(User as ClaimsPrincipal);

    if (Session["SiteSessions"] == null)
    {
        Response.Redirect("/Account/Login");
        Response.End();
    }
}
@{
    ViewBag.Title = "ApproveInvestmentForUser";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table mr-1"></i>
        Approve Plan
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>User Name</th>
                        <th>Email</th>
                        <th>Investment Plan</th>
                        <th>Plan Type</th>
                        <th>Plan Status</th>
                        <th>Action</th>
                        <th>Set Investmen Percentage</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.FirstName @item.LastName
                            </td>
                            <td>
                                @item.UserName
                            </td>
                            <td>
                                @item.Email
                            </td>
                            <td>
                                @item.plan /RS
                            </td>
                            <td>
                                @item.planType
                            </td>
                            <td>
                                @item.planStatus
                            </td>
                            <td>
                                @if (item.planStatus == "Approved")
                                {
                                    <span class="small text-success"> Already Approved</span>
                                }
                                else
                                {
                                    <a href="#" onclick="return approvePlan(@item.UserId);">Approve</a>                                    
                                    <span> | </span>
                                    <a href="#" onclick="return InactivrPlan(@item.planId);">Inactive</a>
                                }                                
                            </td>
                            <td>                                
                                <input class="form-control py-4" id="investmentPercentage" type="number" placeholder="Enter Percentage in numbers" value="@item.InvestPercentage"/>
                                <a href="#" onclick="return SetInvestmentPercentage(@item.UserId);" class="btn btn-primary btn-block">Set Percentage</a>
                                <span class="small text-info">By default the investment percentage is 75%</span>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div id="lblmsg"></div>
    </div>
</div>
<div id="snackbar"></div>
<script>
    function SetInvestmentPercentage(userId) {
        var investPer = $('#investmentPercentage').val();
        if (investPer == "") {
            ShowMessage("", "Please enter investment.");
            return;
        }
        var modelObj = {
                //planAddDate: new date(),
                InvestmentPercentage: investPer,
                userId: userId
            };
            var url = '@Url.Action("UpdateInvestment", "InvestmentPlan")';
             $.ajax({
                type: "POST",
                url: url,
                data: { model: modelObj },
                success: function (result) {
                    if (result.IsSuccess) {
                        ShowMessage('success', "Investment Plan percentage has been updated succesfully");
                        $("#lblmsg").removeClass("small text-danger");
                        $("#lblmsg").addClass("smail text-success");
                        document.getElementById('lblmsg').innerHTML = "Investment Plan percentage has been updated succesfully";
                        $('#ddlPlan').val('');
                        window.location.reload();
                    }
                    else {
                        ShowMessage('', "NOTE: " + result.Message);
                        $("#lblmsg").removeClass("small text-success");
                        $("#lblmsg").addClass("smail text-danger");
                        document.getElementById('lblmsg').innerHTML = "NOTE: " + result.Message;
                    }
                },
                error: function (jqXHR, status, err) {
                    ShowMessage('', "NOTE: " + result.Message);
                    $("#lblmsg").removeClass("small text-success");
                    $("#lblmsg").addClass("smail text-danger");
                    document.getElementById('lblmsg').innerHTML = "NOTE: " + result.Message;
                }
            });
    }

    function approvePlan(userId) {
        if (!confirm('Are you sure you want to approve this Investment plan?')) {
            return false;
        }
        var modelObj = {
                //planAddDate: new date(),
                planStatus: "Approved",
                userId: userId
            };
            var url = '@Url.Action("ApproveInvestmentForUser", "InvestmentPlan")';
             $.ajax({
                type: "POST",
                url: url,
                data: { model: modelObj },
                success: function (result) {
                    if (result.IsSuccess) {
                        ShowMessage('success', "Investment Plan has been approved succesfully");
                        $("#lblmsg").removeClass("small text-danger");
                        $("#lblmsg").addClass("smail text-success");
                        document.getElementById('lblmsg').innerHTML = "Investment Plan has been approved succesfully";
                        $('#ddlPlan').val('');
                        window.location = "/Dashboard/Index";
                    }
                    else {
                        ShowMessage('', "NOTE: " + result.Message);
                        $("#lblmsg").removeClass("small text-success");
                        $("#lblmsg").addClass("smail text-danger");
                        document.getElementById('lblmsg').innerHTML = "NOTE: " + result.Message;
                    }
                },
                error: function (jqXHR, status, err) {
                    ShowMessage('', "NOTE: " + result.Message);
                    $("#lblmsg").removeClass("small text-success");
                    $("#lblmsg").addClass("smail text-danger");
                    document.getElementById('lblmsg').innerHTML = "NOTE: " + result.Message;
                }
            });
    }

    function InactivrPlan(planId) {
        if (!confirm('Are you sure you want to inactive this Investment plan?')) {
            return false;
        }        
            var url = '@Url.Action("InactiveInvestmentForUser", "InvestmentPlan")';
             $.ajax({
                type: "POST",
                url: url,
                data: { planId: planId },
                success: function (result) {
                    if (result.IsSuccess) {
                        ShowMessage('success', "Investment Plan has been approved succesfully");
                        $("#lblmsg").removeClass("small text-danger");
                        $("#lblmsg").addClass("smail text-success");
                        document.getElementById('lblmsg').innerHTML = "Investment Plan has been approved succesfully";
                        $('#ddlPlan').val('');
                        window.location = "/Dashboard/Index";
                    }
                    else {
                        ShowMessage('', "NOTE: " + result.Message);
                        $("#lblmsg").removeClass("small text-success");
                        $("#lblmsg").addClass("smail text-danger");
                        document.getElementById('lblmsg').innerHTML = "NOTE: " + result.Message;
                    }
                },
                error: function (jqXHR, status, err) {
                    ShowMessage('', "NOTE: " + result.Message);
                    $("#lblmsg").removeClass("small text-success");
                    $("#lblmsg").addClass("smail text-danger");
                    document.getElementById('lblmsg').innerHTML = "NOTE: " + result.Message;
                }
            });
    }

    function ShowMessage(type, message) {
             var x = document.getElementById("snackbar");
             x.className = "show";
             x.innerHTML = message;
              setTimeout(function(){ x.className = x.className.replace("show", ""); }, 3000);
        }
</script>

DreamToEarn/Views/InvestmentPlan/SixMonthPlan.cshtml
@model IEnumerable<DreamToEarn.DbModel.InvestmentPlan>
@using System.Security.Claims;
@using DreamToEarn.Helper;
@{
    var user = new AppUser(User as ClaimsPrincipal);

    if (Session["SiteSessions"] == null)
    {
        Response.Redirect("/Account/Login");
        Response.End();
    }
}

@{
    ViewBag.Title = "3 Month Plan";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}


<section id="threeMonthPlan">
    <div class="card-header">
        <i class="fas fa-table mr-1"></i>
        6 Months Investment Plan
    </div>
    <div class="card-body">
        <form>
            <div class="form-group">
                <label class="label-default" for="RefUserName">Choose Investment</label>
                <select class="form-control bx-selection" id="ddlPlan" style="width: 320px;">
                    <option value="">Choose your Investment Plan</option>
                    <option value="30000">30,000/Rs </option>
                    <option value="40000">40,000/Rs </option>
                    <option value="50000">50,000/Rs </option>
                    <option value="60000">60,000/Rs </option>
                </select>
            </div>
            <div class="form-group">
                <div class="form-group mt-4 mb-0"><a class="btn btn-primary btn-block" onclick="return savePlan();" style="width: 80px;">Save</a></div>
                <div class="small">After saving, your request will be pending for admin approve.</div>
                <div id="lblmsg"></div>
            </div>
        </form>
    </div>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Investment Plan
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Investment Plan</th>
                            <th>Plan Type</th>
                            <th>Plan Add Date</th>
                            <th>Plan Active Date</th>
                            <th>Plan Status</th>
                            <th>Plan Is Active?</th>
                        </tr>
                    </thead>
                    @*<tfoot>
                            <tr>
                                <th>Plan</th>
                                <th>Plan Type</th>
                                <th>Plan Add Date</th>
                                <th>Plan Active Date</th>
                                <th>Plan Status</th>
                            </tr>
                        </tfoot>*@
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>

                                <td>@item.plan / RS</td>
                                @if (item.planType == "6Months")
                                {
                                    <td>6 Months Plan</td>
                                }
                                else
                                {
                                    <td>3 Months Plan</td>
                                }
                                <td>@item.planAddDate</td>
                                <td>@item.planActiveDate</td>
                                <td>
                                    @if (item.planStatus == "Pending")
                                    {
                                        <span class="small text-danger">
                                            @item.planStatus
                                        </span>
                                    }
                                    else
                                    {
                                        <span class="small text-success">
                                            @item.planStatus
                                        </span>
                                    }
                                </td>
                                <td>
                                    @if (@item.IsActive == true)
                                    {
                                        <span class="small text-success">
                                            Plan is Active
                                        </span>
                                    }
                                    else
                                    {
                                        <span class="small text-danger">
                                            Plan is inactive
                                        </span>
                                    }
                                </td>

                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div id="snackbar"></div>
</section>
<script>
    function savePlan() {
        var plan = $('#ddlPlan').val();
            if (plan == "") {
                ShowMessage("", "Please choose your plan");
                return false;
        }
        var modelObj = {
                plan: plan,
                planType: "6Months",
                //planAddDate: new date(),
                planStatus: "Pending",
                userId: @user.UserId
            };
            var url = '@Url.Action("threeMonthPlan", "InvestmentPlan")';
             $.ajax({
                type: "POST",
                url: url,
                data: { model: modelObj },
                success: function (result) {
                    if (result.IsSuccess) {
                        ShowMessage('success', "Investment Plan has been added succesfully, it is in pending state, admin will Approve soon.");
                        $("#lblmsg").removeClass("small text-danger");
                        $("#lblmsg").addClass("smail text-success");
                        document.getElementById('lblmsg').innerHTML = "Investment Plan has been added succesfully, it is in pending state, admin will Approve soon.";
                        $('#ddlPlan').val('');
                        window.location.reload();
                    }
                    else {
                        ShowMessage('', "NOTE: " + result.Message);
                        $("#lblmsg").removeClass("small text-success");
                        $("#lblmsg").addClass("smail text-danger");
                        document.getElementById('lblmsg').innerHTML = "NOTE: " + result.Message;
                    }
                },
                error: function (jqXHR, status, err) {
                    ShowMessage('', "NOTE: " + result.Message);
                    $("#lblmsg").removeClass("small text-success");
                    $("#lblmsg").addClass("smail text-danger");
                    document.getElementById('lblmsg').innerHTML = "NOTE: " + result.Message;
                }
            });

        }

        function ShowMessage(type, message) {
             var x = document.getElementById("snackbar");
             x.className = "show";
             x.innerHTML = message;
              setTimeout(function(){ x.className = x.className.replace("show", ""); }, 3000);
        }
</script>