DreamToEarn/Controllers/CommissionController.cs
using DreamToEarn.DbModel;
using DreamToEarn.Helper;
using DreamToEarn.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DreamToEarn.Controllers
{
    public class CommissionController : AppController
    {
        // GET: Commission        
        [Authorize(Roles = "1")]
        public ActionResult Index(int RefUserId)
        {
            ViewBag.Ref = CommissionRepository.GetAllReferrer();
            return View(UsersRepository.GetAllTeam(RefUserId));
        }
        [HttpGet]
        [Authorize(Roles = "1, 2, 3")]
        public ActionResult ViewCommissions()
        {
            return View(CommissionRepository.ViewCommission(CurrentUser.UserId, CurrentUser.Role).AsEnumerable());
        }

        [HttpPost]
        [Authorize(Roles = "1")]
        public JsonResult ApproveCommission(int ComId)
        {
            try
            {
                var Com = CommissionRepository.ApproveCommissions(ComId);
                return Json(new { IsSuccess = true, Message = "Commission Approved successfully!" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { IsSuccess = false, Message = "Commission Approved failed" }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

DreamToEarn/Views/Commission/Index.cshtml
@model IEnumerable<DreamToEarn.DbModel.Team>

@using System.Security.Claims;
@using DreamToEarn.Helper;
@{
    var user = new AppUser(User as ClaimsPrincipal);

    if (Session["SiteSessions"] == null)
    {
        Response.Redirect("/Account/Login");
        Response.End();
    }
}

@{
    ViewBag.Title = "Commission Referrer";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<section id="threeMonthPlan">
    <div class="card-header">
        <i class="fas fa-table mr-1"></i>
        Referrer Team
    </div>
    <div class="card-body">
        <form>
            <div class="form-group">
                <label class="label-default" for="ddlReferrer">Select Referrer</label>
                @*@Html.DropDownList("Referrer", new SelectList(ViewBag.Ref, "UserId", "FirstName"), "Please select", new { @id = "ddlReferrer", @class="form-control bx-selection", @style="width: 320px;", onchange="reloadPage();"})*@
                <select class="form-control bx-selection" id="ddlReferrer" style="width: 320px;" onchange="return reloadPage();">
                    <option value="">Select Referrer</option>
                    @foreach (var item in ViewBag.Ref as IEnumerable<DreamToEarn.DbModel.CommReferrer>)
                    {
                        var selected = "";
                        if (item.UserId.ToDefaultString() == Request.QueryString["RefUserId"])
                        {
                            selected = "selected";
                        }
                        <option value="@item.UserId" @selected>@item.FirstName @item.LastName</option>

                    }

                </select>
            </div>
        </form>
    </div>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Referrer Team
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>User Name</th>
                            <th>Email</th>
                            <th>Investment Plan</th>
                            <th>Plan Type</th>
                            <th>Plan Status</th>
                            <th>Plan IsActive</th>
                            <th>Referred By</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.FirstName @item.LastName
                                </td>
                                <td>
                                    @item.UserName
                                </td>
                                <td>
                                    @item.Email
                                </td>
                                <td>
                                    @item.Plan / RS
                                </td>
                                <td>
                                    @item.planType
                                </td>
                                <td>
                                    @item.IsActive
                                </td>
                                <td>
                                    @if (item.PlanStatus == "Approved")
                                    {
                                        <span class="text-success"> Approved</span>
                                    }
                                    else
                                    {
                                        <span class="text-info"> Pending</span>
                                    }
                                </td>
                                <td>
                                    @item.ReferencedBy
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div id="lblmsg"></div>
    <div id="snackbar"></div>
</section>
<script>
    function reloadPage() {
        var RefUserId = $('#ddlReferrer').val();
        if (RefUserId == "") {
            return false;
        }
        window.location = "/Commission/Index?RefUserId=" + RefUserId;
    }

</script>

DreamToEarn/Views/Commission/ViewCommissions.cshtml
@model IEnumerable<DreamToEarn.DbModel.UsersCommission>

@using System.Security.Claims;
@using DreamToEarn.Helper;
@{
    var user = new AppUser(User as ClaimsPrincipal);

    if (Session["SiteSessions"] == null)
    {
        Response.Redirect("/Account/Login");
        Response.End();
    }
}


@{
    ViewBag.Title = "View Commissions";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table mr-1"></i>
        Referrer Team
    </div>
    <div class="form-group mt-4 mb-0"><a class="btn btn-primary btn-block pull-right" onclick="return PDFExport()" style="width: 120px; padding:10px">View Commission</a></div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>User Name</th>
                        <th>Email</th>
                        <th>Investment Plan</th>
                        <th>Total Commission</th>
                        <th>Commission Date</th>
                        @if (user.Role == "1")
                        {
                            <th>Commission Status</th>
                        }
                        <th>Commission Percentage</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @item.FirstName @item.LastName
                        </td>
                        <td>
                            @item.UserName
                        </td>
                        <td>
                            @item.Email
                        </td>
                        <td>
                            @item.CommissionOnPlan / RS
                        </td>
                        <td>
                            @item.TotalCommission
                        </td>
                        <td>
                            @item.ComDate
                        </td>
                        @if (user.Role == "1")
                        {
                            <td>
                                @if (item.IsApproved == true)
                                {
                                    <span class="text-success"> Approved</span>
                                }
                                else
                                {
                                    <a href="" onclick="return approveCommission(@item.ComId)" class="small text-info">Approve? </a>
                                }
                            </td>
                        }
                        <td>
                            @item.CommissionPercentage
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
            <div id="lblmsg"></div>
            <div id="snackbar"></div>
        </div>
    </div>
</div>
<script>
    function approveCommission(ComId) {
        if (!confirm('Are you sure you want to approve this Commission?')) {
            return false;
        }
            var url = '@Url.Action("ApproveCommission", "Commission")';
             $.ajax({
                type: "POST",
                url: url,
                data: { ComId: ComId },
                success: function (result) {
                    if (result.IsSuccess) {
                        ShowMessage('success', result.Message);
                        $("#lblmsg").removeClass("small text-danger");
                        $("#lblmsg").addClass("smail text-success");
                        document.getElementById('lblmsg').innerHTML = result.Message;
                        $('#ddlPlan').val('');
                        window.location = "/Dashboard/Index";
                    }
                    else {
                        ShowMessage('', "NOTE: " + result.Message);
                        $("#lblmsg").removeClass("small text-success");
                        $("#lblmsg").addClass("smail text-danger");
                        document.getElementById('lblmsg').innerHTML = "NOTE: " + result.Message;
                    }
                },
                error: function (jqXHR, status, err) {
                    ShowMessage('', "NOTE: " + result.Message);
                    $("#lblmsg").removeClass("small text-success");
                    $("#lblmsg").addClass("smail text-danger");
                    document.getElementById('lblmsg').innerHTML = "NOTE: " + result.Message;
                }
            });
    }
   
     function ShowMessage(type, message) {
             var x = document.getElementById("snackbar");
             x.className = "show";
             x.innerHTML = message;
              setTimeout(function(){ x.className = x.className.replace("show", ""); }, 3000);
     }

     function PDFExport()
     {
         alert("Name : _   , UserName : _ , Email : _ , Investment Plan : _ , Total Comission : _ , Commission Date  : _ , Comssion Status : _ , Comssion Percentage : _");
     }
</script>

DreamToEarn/Views/Commission/_ViewAllReferrer.cshtml
@model IEnumerable<DreamToEarn.DbModel.Team>

@using System.Security.Claims;
@using DreamToEarn.Helper;
@{
    var user = new AppUser(User as ClaimsPrincipal);

    if (Session["SiteSessions"] == null)
    {
        Response.Redirect("/Account/Login");
        Response.End();
    }
}


<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table mr-1"></i>
        Referrer Team
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>User Name</th>
                        <th>Email</th>
                        <th>Investment Plan</th>
                        <th>Plan Type</th>
                        <th>Plan Status</th>
                        <th>Plan IsActive</th>
                        <th>Referred By</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.FirstName @item.LastName
                            </td>
                            <td>
                                @item.UserName
                            </td>
                            <td>
                                @item.Email
                            </td>
                            <td>
                                @item.Plan / RS
                            </td>
                            <td>
                                @item.planType
                            </td>
                            <td>
                                @item.IsActive
                            </td>
                            <td>
                                @if (item.PlanStatus == "Approved")
                                {
                                    <span class="text-success"> Approved</span>
                                }
                                else
                                {
                                    <span class="text-info"> Pending</span>
                                }
                            </td>
                            <td>
                                @item.ReferencedBy
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>